version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ruby src/test/rice_cooker_test.rb

